# Generated by Django 2.2.14 on 2020-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_auto_20200810_2011"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bankaccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_id",
                    models.IntegerField(
                        choices=[
                            (1, "BCP"),
                            (2, "BBVA Continental"),
                            (3, "Interbank"),
                            (4, "BanBif"),
                            (5, "MiBanco"),
                            (6, "ScotiaBank"),
                            (7, "Banco Falabella"),
                            (8, "Banco Ripley"),
                            (9, "Banco Azteca"),
                            (10, "Banco Pichincha"),
                            (11, "Banco de Comercio"),
                            (12, "Banco Santander"),
                            (13, "Banco GNB"),
                            (14, "CRAC CAT Perú"),
                            (15, "ICBC PERU BANK"),
                        ],
                        verbose_name="Banco",
                    ),
                ),
                (
                    "type_account",
                    models.IntegerField(
                        choices=[(1, "Crédito"), (2, "Débito")],
                        verbose_name="Tipo de Cuenta",
                    ),
                ),
                (
                    "currency_id",
                    models.IntegerField(
                        choices=[(1, "PEN"), (2, "USD")], verbose_name="Tipo de moneda"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Activo"), (2, "Inactivo"), (3, "Otros")],
                        verbose_name="Estado",
                    ),
                ),
                (
                    "CCI_number",
                    models.IntegerField(
                        max_length=20, verbose_name="Cuenta Interbancaria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco",
                "verbose_name_plural": "Bancos",
            },
        ),
    ]
